In [14]:
import torch
from pathlib import Path
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
PATH = Path("./data")

In [10]:
anime = pd.read_csv(PATH/"anime.csv")

In [12]:
anime = anime.reset_index()

In [19]:
anime.query("Name == 'Shingeki no Kyojin'")

,index,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
7449,7449,16498,Shingeki no Kyojin,8.48,"Action, Military, Mystery, Super Power, Drama,...",Attack on Titan,進撃の巨人,TV,25,"Apr 7, 2013 to Sep 29, 2013",...,470882.0,514879.0,459113.0,220228.0,70768.0,31141.0,11805.0,4637.0,2707.0,4939.0

In [6]:
item_emb = model_state['item_emb.weight']

In [20]:
corr = -cosine_similarity(item_emb, item_emb)[16498, :]
closest = corr.argsort()

In [22]:
closest[:10]

array([16498, 23273, 28171, 25777,  9253,   199, 11757,  7724, 32282,
        3588])

In [25]:
anime.loc[anime.MAL_ID.isin(closest[:10]),:].Name.to_list()

['Sen to Chihiro no Kamikakushi',
 'Soul Eater',
 'Shiki',
 'Steins;Gate',
 'Sword Art Online',
 'Shingeki no Kyojin',
 'Shigatsu wa Kimi no Uso',
 'Shingeki no Kyojin Season 2',
 'Shokugeki no Souma',
 'Shokugeki no Souma: Ni no Sara']

In [26]:
anime.loc[anime.MAL_ID.isin(closest[:10]),:]

,index,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
176,176,199,Sen to Chihiro no Kamikakushi,8.83,"Adventure, Supernatural, Drama",Spirited Away,千と千尋の神隠し,Movie,1,"Jul 20, 2001",...,324768.0,254426.0,182709.0,76025.0,22207.0,7695.0,2393.0,856.0,489.0,1174.0
3155,3155,3588,Soul Eater,7.88,"Action, Fantasy, Comedy, Supernatural, Shounen",Soul Eater,ソウルイーター,TV,51,"Apr 7, 2008 to Mar 30, 2009",...,76241.0,134353.0,201025.0,152877.0,57717.0,24376.0,8704.0,2853.0,1404.0,1351.0
5132,5132,7724,Shiki,7.79,"Horror, Mystery, Supernatural, Thriller, Vampire",Shiki,屍鬼,TV,22,"Jul 9, 2010 to Dec 31, 2010",...,24258.0,42994.0,62037.0,46353.0,19926.0,8725.0,4166.0,1596.0,903.0,734.0
5683,5683,9253,Steins;Gate,9.11,"Thriller, Sci-Fi",Steins;Gate,STEINS;GATE,TV,24,"Apr 6, 2011 to Sep 14, 2011",...,468504.0,275960.0,140914.0,57740.0,21375.0,11126.0,5061.0,2292.0,1678.0,5255.0
6614,6614,11757,Sword Art Online,7.25,"Action, Game, Adventure, Romance, Fantasy",Sword Art Online,ソードアート・オンライン,TV,25,"Jul 8, 2012 to Dec 23, 2012",...,241049.0,236672.0,305386.0,303813.0,188431.0,124819.0,81155.0,44204.0,25371.0,23472.0
7449,7449,16498,Shingeki no Kyojin,8.48,"Action, Military, Mystery, Super Power, Drama,...",Attack on Titan,進撃の巨人,TV,25,"Apr 7, 2013 to Sep 29, 2013",...,470882.0,514879.0,459113.0,220228.0,70768.0,31141.0,11805.0,4637.0,2707.0,4939.0
8883,8883,23273,Shigatsu wa Kimi no Uso,8.74,"Drama, Music, Romance, School, Shounen",Your Lie in April,四月は君の嘘,TV,22,"Oct 10, 2014 to Mar 20, 2015",...,307670.0,250337.0,177967.0,82986.0,30877.0,14233.0,7001.0,2911.0,1562.0,2645.0
9383,9383,25777,Shingeki no Kyojin Season 2,8.45,"Action, Military, Mystery, Super Power, Drama,...",Attack on Titan Season 2,進撃の巨人 Season2,TV,12,"Apr 1, 2017 to Jun 17, 2017",...,239823.0,308956.0,304020.0,135241.0,38504.0,12841.0,5160.0,1716.0,839.0,1804.0
9732,9732,28171,Shokugeki no Souma,8.29,"Ecchi, School, Shounen",Food Wars! Shokugeki no Soma,食戟のソーマ,TV,24,"Apr 4, 2015 to Sep 26, 2015",...,115573.0,195681.0,228781.0,116773.0,33230.0,12166.0,4424.0,1700.0,1033.0,1501.0
11309,11309,32282,Shokugeki no Souma: Ni no Sara,8.21,"Ecchi, School, Shounen",Food Wars! The Second Plate,食戟のソーマ 弍ノ皿,TV,13,"Jul 2, 2016 to Sep 24, 2016",...,72244.0,133542.0,175909.0,91564.0,24546.0,7342.0,2108.0,707.0,383.0,710.0

In [27]:
corr = -cosine_similarity(item_emb, item_emb)[23273, :]
closest = corr.argsort()

In [28]:
anime.loc[anime.MAL_ID.isin(closest[:10]),:].Name.to_list()

['Steins;Gate',
 'Sakura-sou no Pet na Kanojo',
 'Shingeki no Kyojin',
 'Shigatsu wa Kimi no Uso',
 'Shingeki no Kyojin Season 2',
 'Shokugeki no Souma',
 'Shokugeki no Souma: Ni no Sara',
 'Sakamoto Desu ga?',
 'Shelter',
 'Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai']